### ISSUE TITLE
Why use numpy?

### ISSUE THREAD

**Issue by devleaks** [pyturf/pyturf#48]
Hello,

I'm no python expert but I'd love to know why we need to use numpy.sin rather than math.sin in some packages.
Added numpy to turf adds a faily big dependency.

It is the same for rtree. It adds considerable dependency for, so far, a single use in lineintersect. Even turfjs does not use any rtree library. Python rtree lib relies on a "heavy" libspatialindex library. I could not find a python only rtree library.

Thank you for your input.

Regards,
Pierre

**Comment by SteffenHaeussler** [comment]
Hi Pierre,

Thanks for your interest in our project. 

I agree, the numpy dependency makes not soo much sense. I guess, we introduced it out of convenience and we were not very strict in our code reviews. 😅  We use numpy only for standard operations. Changing from numpy to math would reduce the dependencies and improve the code quality. You are right and your suggestion would be a better solution. Thanks for pointing it out, I will create an issue. :)  

I also agree with the rtree library and the "heavy" libspatialindex library. I also don't like the library much, but I never had any problems with it in my work-related experience. I'm not aware of any other "production"-ready implementation in python. Until we find a more suitable implementation, we have to use this one.

I disagree. Turfjs uses an implementation of rtrees [rtrees](https://github.com/Turfjs/turf/blob/master/packages/turf-line-intersect/index.ts#L69) . Here is the link to the [repo](https://github.com/DenisCarriere/geojson-rbush). 

Again, thanks for your interest. We both are a bit slow at the moment with the implementation of missing libraries. I started a new job and drown in work tasks. If I get some idle time, I would continue working here.

Best, Steffen
