### ISSUE TITLE
Should allow for more than just two coordinates for Points

### ISSUE THREAD

**Issue by devleaks** [pyturf/pyturf#63]
An OPTIONAL third-position element SHALL be the height in meters above or below the WGS 84 reference ellipsoid.
(https://datatracker.ietf.org/doc/rfc7946/?include_text=1)

(I use it a lot, so I adjusted _check_input for Point.)

**Comment by SteffenHaeussler** [comment]
Thanks for your contribution. I'm currently on holidays and travelling. Please give me some days for this review.

**Comment by SteffenHaeussler** [comment]
Thanks for your contribution. I updated the code and released a new version.
