### ISSUE TITLE
Pip install error on TypeVar definition

### ISSUE THREAD

**Issue by devleaks** [pyturf/pyturf#65]
in _polygon_to_line.py", line 18:

PolygonFeature = TypeVar(Dict, "PolygonFeature", Polygon, MultiPolygon)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      TypeError: typevar() argument 'name' must be str, not _SpecialGenericAlias

**Comment by SteffenHaeussler** [comment]
Thank you for the fix. 

It can take some time until this fix will be published. PyPi changed their authentication towards API-Tokens only. My PyPi account is not linked with the project, so I can't fix this issue. Only @diogomatoschaves can solve this issue.

**Comment by diogomatoschaves** [comment]
@SteffenHaeussler all working now.
